In [ ]:
## Q.1) Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
import numpy as np

In [ ]:
# Create a NumPy array of integers from 0 to 5
arr = np.arange(6)

# Print the data type of the array
print(arr.dtype)

int64


In [ ]:
## Q.2) Given a NumPy array 'arr', check if its data type is float64.
##      arr = np.array([1.5, 2.6, 3.7])
import numpy as np
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type is float64
if arr.dtype == np.float64:
    print("Data type is float64")
else:
    print("Data type is not float64")

Data type is float64


In [ ]:
## Q.3) Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
import numpy as np
# Create a NumPy array with complex128 data type
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [ ]:
## Q.4) Convert an existing NumPy array 'arr' of integers to float32 data type.
import numpy as np

# Create an integer NumPy array
arr = np.array([21, 22, 23, 24, 25])
print("Original array (integer):", arr)
print("Data type:", arr.dtype)

# Convert the array to float32
arr_float32 = arr.astype(np.float32)
print("Converted array (float32):", arr_float32)
print("Data type:", arr_float32.dtype)

Original array (integer): [21 22 23 24 25]
Data type: int64
Converted array (float32): [21. 22. 23. 24. 25.]
Data type: float32


In [ ]:
## Q.5) Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
import numpy as np

# Create a float64 NumPy array
arr = np.array([1.23456789, 2.3456789, 3.456789])
print("Original array (float64):", arr)
print("Data type:", arr.dtype)

# Convert the array to float32
arr_float32 = arr.astype(np.float32)
print("Converted array (float32):", arr_float32)
print("Data type:", arr_float32.dtype)

Original array (float64): [1.23456789 2.3456789  3.456789  ]
Data type: float64
Converted array (float32): [1.2345679 2.3456788 3.456789 ]
Data type: float32


In [ ]:
## Q.6) Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
import numpy as np

def array_attributes(arr):
    shape = arr.shape       # Get the shape of the array
    size = arr.size         # Get the total number of elements in the array
    dtype = arr.dtype       # Get the data type of the elements in the array

    return shape, size, dtype

# Example;
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)

print("Shape:", shape)
print("Size:", size)
print("Data Type:", dtype)


Shape: (2, 3)
Size: 6
Data Type: int64


In [ ]:
## Q.7) Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
import numpy as np

def array_dimension(arr):
    return arr.ndim  # Return the number of dimensions of the array

# Example;
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimension = array_dimension(arr)

print("Dimensionality:", dimension)

Dimensionality: 2


In [ ]:
## Q.8) Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize    # Get the size of one array element in bytes
    total_size = arr.nbytes     # Get the total size of the array in bytes

    return item_size, total_size

# Example;
arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)

print("Item Size:", item_size, "bytes")
print("Total Size:", total_size, "bytes")

Item Size: 8 bytes
Total Size: 48 bytes


In [ ]:
## Q.9) Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
import numpy as np

def array_strides(arr):
    return arr.strides  # Return the strides of the array

# Example;
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)

print("Strides:", strides)

Strides: (24, 8)


In [ ]:
## Q.10) Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
import numpy as np

def shape_stride_relationship(arr):
    shape = arr.shape    # Get the shape of the array
    strides = arr.strides # Get the strides of the array

    return shape, strides

# Example;
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)

print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (24, 8)


In [ ]:
## Q.11) Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)  # Create and return a NumPy array of zeros with n elements

# Example;
n = 5
zeros_array = create_zeros_array(n)

print("Array of zeros:", zeros_array)

Array of zeros: [0. 0. 0. 0. 0.]


In [ ]:
## Q.12) Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and
##      generates a 2D NumPy array filled with ones of size `rows x cols`.
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))  # Create and return a 2D NumPy array of ones with specified rows and columns

# Example;
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print("2D Array of ones:")
print(ones_matrix)

2D Array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
## Q.13) Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
## creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)  # Create and return a NumPy array with the specified range and step

# Example;
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print("Range array:", range_array)

Range array: [0 2 4 6 8]


In [ ]:
## Q.14) Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
## arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)  # Create and return a NumPy array with num equally spaced values

# Example;
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)

print("Linear space array:", linear_space_array)

Linear space array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
## Q.15) Create a function `create_identity_matrix` that takes an integer `n` as input and generates a
##       square identity matrix of size `n x n` using `numpy.eye`.
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)  # Create and return an n x n identity matrix

# Example;
n = 4
identity_matrix = create_identity_matrix(n)

print("Identity matrix:")
print(identity_matrix)

Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
## Q.16) Write a function that takes a Python list and converts it into a NumPy array.
import numpy as np

def list_to_numpy_array(py_list):
    return np.array(py_list)  # Convert the Python list to a NumPy array and return it

# Example;
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)

print("NumPy array:", numpy_array)

NumPy array: [1 2 3 4 5]


In [ ]:
## Q.17) Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
import numpy as np

# Create an original NumPy array
original_array = np.array([10, 20, 30, 40, 50])

# Create a view of the original array
view_array = original_array.view()

# Modify the view array
view_array[0] = 99

# Print both arrays to observe the effect
print("Original array:", original_array)
print("View array:", view_array)

Original array: [99 20 30 40 50]
View array: [99 20 30 40 50]


In [ ]:
## Q.18) Write a function that takes two NumPy arrays and concatenates them along a specified axis.
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)  # Concatenate the two arrays along the specified axis

# Example;
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
result_axis_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", result_axis_0)

# Concatenate along axis 1 (columns)
result_axis_1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:\n", result_axis_1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
## Q.19) Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
import numpy as np

# Create two NumPy arrays with different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
arr2 = np.array([[7, 8], [9, 10]])       # Shape: (2, 2)

# Concatenate the arrays horizontally (along axis=1)
result = np.concatenate((arr1, arr2), axis=1)

# Print the result
print("Concatenated array:\n", result)

Concatenated array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [ ]:
## Q.20) Write a function that vertically stacks multiple NumPy arrays given as a list.
import numpy as np

def vertical_stack_arrays(array_list):
    return np.vstack(array_list)  # Vertically stack the list of arrays

# Example;
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

# Vertically stack the arrays
result = vertical_stack_arrays([arr1, arr2, arr3])

# Print the result
print("Vertically stacked array:\n", result)

Vertically stacked array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
## Q.21) Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
import numpy as np

def create_integer_range(start, stop, step):
    return np.arange(start, stop + 1, step)  # Create an array with a given step size, inclusive of the stop value

# Example;
start = 1
stop = 10
step = 2
range_array = create_integer_range(start, stop, step)

print("Integer range array:", range_array)

Integer range array: [1 3 5 7 9]


In [ ]:
## Q.22) Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
import numpy as np

def generate_equal_spacing():
    return np.linspace(0, 1, 10)  # Generate 10 equally spaced values between 0 and 1 (inclusive)

# Example;
equal_spacing_array = generate_equal_spacing()

print("Equally spaced array:", equal_spacing_array)

Equally spaced array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
## Q.23) Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
import numpy as np

def generate_log_spacing():
    return np.logspace(0, 3, 5)  # Generate 5 logarithmically spaced values between 10^0 (1) and 10^3 (1000)

# Example;
log_spacing_array = generate_log_spacing()

print("Logarithmically spaced array:", log_spacing_array)

Logarithmically spaced array: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
## Q.24) Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns,
##       where the values are random integers between 1 and 100.
import numpy as np
import pandas as pd

# Generate a NumPy array with random integers between 1 and 100
np.random.seed(0)  # For reproducibility
data = np.random.randint(1, 101, size=(5, 3))  # 5 rows, 3 columns

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

# Print the DataFrame
print("Pandas DataFrame:")
print(df)

Pandas DataFrame:
   Column1  Column2  Column3
0       45       48       65
1       68       68       10
2       84       22       37
3       88       71       89
4       89       13       59


In [ ]:
## Q.25) Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
##       with zeros. Use NumPy operations within the Pandas DataFrame.
import numpy as np
import pandas as pd

def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example;
# Create a sample DataFrame with some negative values
data = {
    'A': [10, -5, 20, -1, 30],
    'B': [-10, 15, -20, 25, -30],
    'C': [0, 5, -10, 15, -20]
}
df = pd.DataFrame(data)

# Replace negative values in column 'A' with zeros
df_modified = replace_negatives_with_zero(df, 'A')

print("Modified DataFrame:")
print(df_modified)

Modified DataFrame:
    A   B   C
0  10 -10   0
1   0  15   5
2  20 -20 -10
3   0  25  15
4  30 -30 -20


In [ ]:
## Q.26) Access the 3rd element from the given NumPy array; arr = np.array([10, 20, 30, 40, 50])
import numpy as np

# Create the NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)

The 3rd element is: 30


In [ ]:
## Q.27) Retrieve the element at index (1, 2) from the 2D NumPy array: arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
import numpy as np

# Create the 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print("Element at index (1, 2) is:", element)

Element at index (1, 2) is: 6


In [ ]:
## Q.28) Using boolean indexing, extract elements greater than 5 from the given NumPy array: arr = np.array([3, 8, 2, 10, 5, 7])
import numpy as np

# Create the NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Use boolean indexing to extract elements greater than 5
filtered_elements = arr[arr > 5]

print("Elements greater than 5:", filtered_elements)

Elements greater than 5: [ 8 10  7]


In [ ]:
## Q.29) Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
##       arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np

# Create the NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slice the array to get elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]  # Note: the end index is exclusive, so use 6 to include the element at index 5

print("Sliced array:", sliced_array)

Sliced array: [3 4 5 6]


In [ ]:
## Q.30) Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
##       arr_2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
import numpy as np

# Create the 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice the array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]  # Rows 0 to 1 (inclusive) and columns 1 to 2 (inclusive)

print("Sub-array:")
print(sub_array)

Sub-array:
[[2 3]
 [5 6]]


In [ ]:
## Q.31) Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
import numpy as np

def extract_elements_by_indices(arr_2d, indices):
    # Extract elements based on indices
    return arr_2d[indices[:, 0], indices[:, 1]]

# Example;
# Given 2D array
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Indices to extract: (row, column)
indices = np.array([[0, 1],  # Corresponds to 20
                    [1, 2],  # Corresponds to 60
                    [2, 0]]) # Corresponds to 70

# Extract elements using the function
extracted_elements = extract_elements_by_indices(arr_2d, indices)

print("Extracted elements:", extracted_elements)

Extracted elements: [20 60 70]


In [ ]:
## Q.32) Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
import numpy as np

def filter_elements_greater_than(arr, threshold):
    # Use boolean indexing to filter elements greater than the threshold
    return arr[arr > threshold]

# Example;
# Given 1D array
arr = np.array([2, 7, 11, 8, 14, 22, 9])

# Threshold for filtering
threshold = 9

# Filter elements greater than the threshold
filtered_elements = filter_elements_greater_than(arr, threshold)

print("Filtered elements greater than", threshold, ":", filtered_elements)

Filtered elements greater than 9 : [11 14 22]


In [ ]:
## Q.33) Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
import numpy as np

def extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices):
    # Ensure indices are arrays
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)
    depth_indices = np.array(depth_indices)

    # Extract elements using the indices
    return arr_3d[row_indices, col_indices, depth_indices]

# Example;
# Create a 3D NumPy array
arr_3d = np.array([[[11, 12, 13],
                    [14, 15, 16],
                    [17, 18, 19]],

                   [[20, 21, 22],
                    [23, 24, 25],
                    [26, 27, 28]],

                   [[29, 30, 31],
                    [32, 33, 34],
                    [35, 36, 37]]])

# Indices for each dimension
row_indices = [0, 1, 2]
col_indices = [1, 2, 0]
depth_indices = [2, 1, 0]

# Extract elements using the function
extracted_elements = extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices)

print("Extracted elements:", extracted_elements)

Extracted elements: [16 27 29]


In [ ]:
## Q.34) Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np

def filter_elements_with_conditions(arr, condition1, condition2):
    # Apply both conditions using logical AND
    combined_condition = condition1 & condition2
    # Filter elements based on the combined condition
    return arr[combined_condition]

# Example;
# Given 1D array
arr = np.array([3, 8, 5, 12, 1, 16, 9, 20])

# Define two conditions
condition1 = arr > 6       # Elements greater than 3
condition2 = arr % 2 == 0  # Elements that are even

# Filter elements where both conditions are satisfied
filtered_elements = filter_elements_with_conditions(arr, condition1, condition2)

print("Filtered elements where both conditions are satisfied:", filtered_elements)

Filtered elements where both conditions are satisfied: [ 8 12 16 20]


In [ ]:
## Q.35) Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
import numpy as np

def extract_elements_2d(arr_2d, row_indices, col_indices):
    # Ensure indices are arrays
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)

    # Extract elements using the row and column indices
    return arr_2d[row_indices, col_indices]

# Example;
# Create a 2D NumPy array
arr_2d = np.array([[11, 21, 31],
                   [41, 51, 61],
                   [71, 81, 91]])

# Indices for rows and columns
row_indices = [0, 1, 2]
col_indices = [1, 2, 0]

# Extract elements using the function
extracted_elements = extract_elements_2d(arr_2d, row_indices, col_indices)

print("Extracted elements:", extracted_elements)

Extracted elements: [21 61 71]


In [ ]:
## Q.36) Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
import numpy as np

# Create a 2D NumPy array of shape (3, 3)
arr = np.array([[5, 6, 7],
                [8, 9, 10],
                [11, 12, 13]])

# Scalar value to add
scalar = 10

# Add the scalar value to each element of the array using broadcasting
result = arr + scalar

print("Original array:")
print(arr)
print("\nArray after adding scalar value:")
print(result)

Original array:
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

Array after adding scalar value:
[[15 16 17]
 [18 19 20]
 [21 22 23]]


In [1]:
## Q.37) Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2
##       by the corresponding element in arr1 using NumPy broadcasting.
import numpy as np

# Define the arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[5, 6, 7, 8],   # Shape (3, 4)
                 [2, 9, 1, 3],
                 [3, 1, 7, 5]])

# Reshape arr1 to be broadcastable over arr2
arr1_reshaped = arr1.T  # Transpose to shape (3, 1)

# Perform the multiplication
result = arr1_reshaped * arr2

print(result)

[[10 12 14 16]
 [ 6 27  3  9]
 [12  4 28 20]]


In [ ]:
##Q.38) Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
import numpy as np

# Define arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape (4, 3)

# Reshape arr1 to shape (4, 1) to enable broadcasting with arr2
arr1_reshaped = arr1[:, :arr2.shape[1]]  # Select only the first 3 elements to match arr2's column count

# Add arr1 to each row of arr2
result = arr2 + arr1_reshaped

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult after broadcasting and addition:")
print(result)

arr1:
[[1 2 3 4]]

arr2:
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]

Result after broadcasting and addition:
[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


In [ ]:
## Q.39) Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
import numpy as np

# Define arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])       # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult after broadcasting and addition:")
print(result)

arr1:
[[1]
 [2]
 [3]]

arr2:
[[4 5 6]]

Result after broadcasting and addition:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
## Q.40) Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
##       broadcasting. Handle the shape incompatibility.
import numpy as np

# Define arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[10, 20],       # Shape (2, 2)
                 [30, 40]])

# Reshape arr2 to (2, 1, 2) to enable broadcasting
arr2_reshaped = arr2[:, :, np.newaxis]  # Add a new axis for broadcasting

# Perform multiplication using broadcasting
result = arr1 * arr2_reshaped

print("arr1:")
print(arr1)
print("\narr2 reshaped:")
print(arr2_reshaped)
print("\nResult after broadcasting and multiplication:")
print(result)

arr1:
[[1 2 3]
 [4 5 6]]

arr2 reshaped:
[[[10]
  [20]]

 [[30]
  [40]]]

Result after broadcasting and multiplication:
[[[ 10  20  30]
  [ 80 100 120]]

 [[ 30  60  90]
  [160 200 240]]]


In [ ]:
## Q.41) Calculate column wise mean for the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

column_wise_mean = np.mean(arr, axis=0)

print(column_wise_mean)

[2.5 3.5 4.5]


In [ ]:
## Q.42) Find maximum value in each row of the given array: arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

row_wise_max = np.max(arr, axis=1)

print(row_wise_max)

[3 6]


In [ ]:
## Q.43) For the given array, find indices of maximum value in each column.
##        arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

column_max_indices = np.argmax(arr, axis=0)

print(column_max_indices)

[1 1 1]


In [ ]:
## Q.44) For the given array, apply custom function to calculate moving sum along rows.
##       arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

moving_sum = np.cumsum(arr, axis=1)

print(moving_sum)

[[ 1  3  6]
 [ 4  9 15]]


In [ ]:
## Q.45) In the given array, check if all elements in each column are even.
##        arr = np.array([[2, 4, 6], [3, 5, 7]])
import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if all elements in each column are even
is_even_in_columns = np.all(arr % 2 == 0, axis=0)

print(is_even_in_columns)

[False False False]


In [ ]:
## Q.46) Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
##        original_array = np.array([1, 2, 3, 4, 5, 6])
import numpy as np

def reshape_matrix(original_array, m, n):
  """Reshapes a 1D array into a matrix of dimensions m rows and n columns.

  Args:
    original_array: The original 1D array.
    m: The number of rows in the reshaped matrix.
    n: The number of columns in the reshaped matrix.

  Returns:
    The reshaped matrix.

  Raises:
    ValueError: If the product of m and n is not equal to the length of the original array.
  """

  if m * n != len(original_array):
    raise ValueError("The product of m and n must be equal to the length of the original array.")

  return original_array.reshape(m, n)

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = reshape_matrix(original_array, 2, 3)

print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
## Q.47) Create a function that takes a matrix as input and returns the flattened array.
##        input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

def flatten_matrix(matrix):
  """Flattens a matrix into a 1D array.
  Args:
    matrix: The input matrix.
  Returns:
    The flattened array.
  """

  return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)

print(flattened_array)

[1 2 3 4 5 6]


In [ ]:
## Q.48) Write a function that concatenates two given arrays along a specified axis.
##       array1 = np.array([[1, 2], [3, 4]]) and array2 = np.array([[5, 6], [7, 8]])
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
  """Concatenates two given arrays along a specified axis.

  Args:
    array1: The first array.
    array2: The second array.
    axis: The axis along which to concatenate the arrays.

  Returns:
    The concatenated array.

  Raises:
    ValueError: If the arrays have incompatible shapes for the specified axis.
  """

  return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array = concatenate_arrays(array1, array2, axis=1)

print(concatenated_array)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
## Q.49) Create a function that splits an array into multiple sub-arrays along a specified axis.
##       original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
import numpy as np

def split_array(array, axis, num_splits):
  """Splits an array into multiple sub-arrays along a specified axis.

  Args:
    array: The original array.
    axis: The axis along which to split the array.
    num_splits: The number of sub-arrays to create.

  Returns:
    A list of sub-arrays.

  Raises:
    ValueError: If the array cannot be split into the specified number of sub-arrays along the given axis.
  """

  if array.shape[axis] % num_splits != 0:
    raise ValueError("The array cannot be split into the specified number of sub-arrays along the given axis.")

  split_size = array.shape[axis] // num_splits
  return np.split(array, num_splits, axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_arrays = split_array(original_array, axis=0, num_splits=3)

print(sub_arrays)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
## Q.50) Write a function that inserts and then deletes elements from a given array at specified indices.
##        original_array = np.array([1, 2, 3, 4, 5])
##        indices_to_insert = [2, 4] , values_to_insert = [10, 11] , indices_to_delete = [1, 3]
import numpy as np

def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
  """Inserts and then deletes elements from a given array at specified indices.

  Args:
    original_array: The original array.
    indices_to_insert: A list of indices where to insert the new elements.
    values_to_insert: A list of values to insert.
    indices_to_delete: A list of indices where to delete elements.

  Returns:
    The modified array.

  Raises:
    ValueError: If the indices to insert or delete are out of bounds.
  """

  # Insert elements
  for index, value in zip(indices_to_insert, values_to_insert):
    if index < 0 or index > len(original_array):
      raise ValueError("Index out of bounds for insertion.")
    original_array = np.insert(original_array, index, value)

  # Delete elements
  for index in sorted(indices_to_delete, reverse=True):
    if index < 0 or index >= len(original_array):
      raise ValueError("Index out of bounds for deletion.")
    original_array = np.delete(original_array, index)

  return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print(modified_array)

[ 1 10 11  4  5]


In [ ]:
## Q.51) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
##        Perform element-wise addition between `arr1` and `arr2`.
import numpy as np

# Create array arr1 with random integers
arr1 = np.random.randint(low=0, high=100, size=10)

# Create array arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise addition
result = arr1 + arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [96 60  8 99 66  9 10 57 68 81]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result: [ 97  62  11 103  71  15  17  65  77  91]


In [ ]:
## Q.52) Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
##        from 1 to 10. Subtract `arr2` from `arr1` element-wise.
import numpy as np

# Create array arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create array arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Subtract arr2 from arr1 element-wise
result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
## Q.53) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
##        Perform element-wise multiplication between `arr1` and `arr2`.
import numpy as np

# Create array arr1 with random integers
arr1 = np.random.randint(low=0, high=30, size=5)

# Create array arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [18 15 20 27  9]
arr2: [1 2 3 4 5]
Result: [ 18  30  60 108  45]


In [ ]:
## Q.54) Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
##        to 5. Perform element-wise division of `arr1` by `arr2`.
import numpy as np

# Create array arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create array arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division of arr1 by arr2
result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result: [2. 2. 2. 2. 2.]


In [ ]:
## Q.55) Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
##        reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
import numpy as np

# Create the arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# Perform element-wise exponentiation
result = arr1 ** arr2
# The element-wise exponentiation will calculate:
#  1^5, 2^4, 3^3, 4^2, 5^1

print(result)

[ 1 16 27 16  5]


In [ ]:
## Q.56) Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
##        arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
import numpy as np

def count_substring_occurrences(arr, substring):
    # Use vectorized string operation to count occurrences
    count = np.char.count(arr, substring)
    # Sum all counts to get the total occurrences in the array
    total_count = np.sum(count)
    return total_count

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

result = count_substring_occurrences(arr, substring)
print(result)

3


In [ ]:
## Q.57) Write a function that extracts uppercase characters from a NumPy array of strings.
##        arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
import numpy as np

def extract_uppercase(arr):
    # Use a vectorized function to apply a list comprehension that extracts uppercase letters
    extract_upper = np.vectorize(lambda x: ''.join([char for char in x if char.isupper()]))
    # Apply the function to the array
    uppercase_arr = extract_upper(arr)
    return uppercase_arr

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

result = extract_uppercase(arr)
print(result)

['H' 'W' 'OAI' 'GPT']


In [ ]:
## Q.58) Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
##        arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Use np.char.replace to replace occurrences of old_substring with new_substring
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr

# Example;
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'pineapple'
new_substring = 'mango'

result = replace_substring(arr, old_substring, new_substring)
print(result)

['apple' 'banana' 'grape' 'mango']


In [ ]:
## Q.59) Write a function that concatenates strings in a NumPy array element-wise.
##       arr1 = np.array(['Hello', 'World']) and arr2 = np.array(['Open', 'AI'])
import numpy as np

def concatenate_arrays(arr1, arr2):
    # Use np.char.add to concatenate the arrays element-wise
    concatenated_arr = np.char.add(arr1, arr2)
    return concatenated_arr

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_arrays(arr1, arr2)
print(result)

['HelloOpen' 'WorldAI']


In [ ]:
## Q. 60) Write a function that finds the length of the longest string in a NumPy array.
##         arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np
def longest_string_length(array):

  return max(len(string) for string in array)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

longest_length = longest_string_length(arr)

print(longest_length)

9


In [ ]:
## Q.61) Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
##        standard deviation of the dataset using NumPy's functions.
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 489.68
Median: 470.0
Variance: 81604.61759999998
Standard Deviation: 285.6652194440198


In [ ]:
## Q.62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
data = np.random.randint(1, 101, size=50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")

25th Percentile: 35.5
75th Percentile: 73.5


In [ ]:
##Q.63)Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
import numpy as np

# Create two arrays representing two sets of variables
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4, 6, 8, 10])

# Compute the correlation coefficient
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]

print("Correlation coefficient:", correlation_coefficient)

Correlation coefficient: 0.9999999999999999


In [ ]:
## Q.64) Create two matrices and perform matrix multiplication using NumPy's `dot` function.
import numpy as np

# Create two matrices
matrix1 = np.array([[2, 3, 4],
                    [7, 8, 9]])

matrix2 = np.array([[10, 11],
                    [6, 1],
                    [12, 5]])

# Perform matrix multiplication using np.dot
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of Matrix Multiplication:")
print(result)

Matrix 1:
[[2 3 4]
 [7 8 9]]

Matrix 2:
[[10 11]
 [ 6  1]
 [12  5]]

Result of Matrix Multiplication:
[[ 86  45]
 [226 130]]


In [ ]:
##Q.65)Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
import numpy as np

# Generate an array of 50 random integers between 10 and 1000
data = np.random.randint(10, 1001, size=50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)  # This is the median
percentile_90 = np.percentile(data, 90)

# Calculate the first (25th percentile) and third (75th percentile) quartiles
first_quartile = np.percentile(data, 25)
third_quartile = np.percentile(data, 75)

print("Data:", data)
print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile (25th Percentile): {first_quartile}")
print(f"Third Quartile (75th Percentile): {third_quartile}")

Data: [933 292 244 813 137 694 908 191 263 993 228 502 778 321 781 875 855 613
 461 135 401 909 261 363 284 373 662 364 781 204 838 284 108 879 750 986
 778 142 876 444 660 678 851 623 998 945 837 432 541 950]
10th Percentile: 202.70000000000002
50th Percentile (Median): 641.5
90th Percentile: 934.2
First Quartile (25th Percentile): 299.25
Third Quartile (75th Percentile): 847.75


In [ ]:
## Q. 66) Create a NumPy array of integers and find the index of a specific element.
import numpy as np

# Create a NumPy array of integers
arr = np.array([11, 12, 13, 14, 15, 16])

# Specify the element you want to find the index of
element_to_find = 15

# Find the index of the specific element
index = np.where(arr == element_to_find)[0]

print(f"Array: {arr}")
print(f"Index of element {element_to_find}: {index}")

Array: [11 12 13 14 15 16]
Index of element 15: [4]


In [ ]:
## Q. 67) Generate a random NumPy array and sort it in ascending order.
import numpy as np

# Generate a random NumPy array with 10 integers between 1 and 100
random_array = np.random.randint(1, 51, size=20)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Original Array:", random_array)
print("Sorted Array:", sorted_array)

Original Array: [39 19 23 42 31 46 42 26 24 50 50 43 28 35 16 17  2 19  5  8]
Sorted Array: [ 2  5  8 16 17 19 19 23 24 26 28 31 35 39 42 42 43 46 50 50]


In [ ]:
## Q. 68) Filter elements >20  in the given NumPy array:-  arr = np.array([12, 25, 6, 42, 8, 30])
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_arr = arr[arr > 20]

print("Filtered Array:", filtered_arr)

Filtered Array: [25 42 30]


In [ ]:
##Q.69) Filter elements which are divisible by 3 from a given NumPy array:-  arr = np.array([1, 5, 8, 12, 15])
import numpy as np
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

print("Filtered Array:", filtered_arr)

Filtered Array: [12 15]


In [ ]:
## Q.70) Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array:-  arr = np.array([10, 20, 30, 40, 50])
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# Filter elements that are ≥ 20 and ≤ 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Filtered Array:", filtered_arr)

Filtered Array: [20 30 40]


In [ ]:
##Q.71) For the given NumPy array, check its byte order using the `dtype` attribute byte order:- arr = np.array([1, 2, 3])
import numpy as np
arr = np.array([1, 2, 3])

# Check the byte order using the dtype attribute
byte_order = arr.dtype.byteorder

print("Byte Order:", byte_order)

Byte Order: =


In [ ]:
##Q.72) For the given NumPy array, perform byte swapping in place using `byteswap()`:- arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np

# Given NumPy array with specified dtype
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(inplace=True)

print("Byte-swapped Array:", arr)

Byte-swapped Array: [16777216 33554432 50331648]


In [ ]:
## Q.73) For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
##        arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap the byte order without modifying the original array
swapped_arr = arr.newbyteorder()

print("Original Array:", arr)
print("Byte-swapped Array:", swapped_arr)

Original Array: [1 2 3]
Byte-swapped Array: [16777216 33554432 50331648]


In [ ]:
## Q.74) For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
##         arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's endianness
system_endianness = np.dtype(np.int32).byteorder

# Conditionally swap the byte order based on system endianness
if system_endianness == '=':  # Native endianness
    swapped_arr = arr.newbyteorder('>')
else:
    swapped_arr = arr

print("Original Array:", arr)
print("Swapped Array:", swapped_arr)

Original Array: [1 2 3]
Swapped Array: [16777216 33554432 50331648]


In [ ]:
##Q.75) For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
##         arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's native byte order
system_byteorder = np.dtype(np.int32).byteorder

# Check the array's byte order
array_byteorder = arr.dtype.byteorder

# Determine if byte swapping is necessary
if array_byteorder == system_byteorder:
    print("Byte swapping is not necessary.")
else:
    print("Byte swapping is necessary.")

print(f"System Byte Order: {system_byteorder}")
print(f"Array Byte Order: {array_byteorder}")

Byte swapping is not necessary.
System Byte Order: =
Array Byte Order: =


In [ ]:
## Q.76) Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
##        an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
import numpy as np

# Create a NumPy array with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[2] = 25

# Check if modifying copy_arr affects arr1
print("Original Array (arr1):", arr1)
print("Modified Copy (copy_arr):", copy_arr)

Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy (copy_arr): [ 1  2 25  4  5  6  7  8  9 10]


In [ ]:
## Q. 77)Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
##        the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
import numpy as np

# Create a 2D NumPy array of shape (3, 3) with random integers
matrix = np.random.randint(1, 10, size=(3, 3))

# Extract a slice from the matrix (for example, the first two rows and columns)
view_slice = matrix[:2, :2]

# Print the original matrix and the slice before modification
print("Original Matrix:")
print(matrix)
print("\nView Slice Before Modification:")
print(view_slice)

# Modify an element in the view_slice
view_slice[0, 0] = 50

# Print the original matrix and the slice after modification
print("\nOriginal Matrix After Modification:")
print(matrix)
print("\nView Slice After Modification:")
print(view_slice)

Original Matrix:
[[3 1 7]
 [7 9 6]
 [6 7 9]]

View Slice Before Modification:
[[3 1]
 [7 9]]

Original Matrix After Modification:
[[50  1  7]
 [ 7  9  6]
 [ 6  7  9]]

View Slice After Modification:
[[50  1]
 [ 7  9]]


In [ ]:
## Q. 78) Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
##         `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
import numpy as np

# Create a NumPy array of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice from array_a (for example, the first two rows and columns)
view_b = array_a[:2, :2]

# Print the original array and the slice before modification
print("Original Array (array_a):")
print(array_a)
print("\nView Slice Before Broadcasting:")
print(view_b)

# Broadcast the addition of 5 to view_b
view_b += 5

# Print the original array and the slice after broadcasting
print("\nOriginal Array (array_a) After Broadcasting:")
print(array_a)
print("\nView Slice (view_b) After Broadcasting:")
print(view_b)

Original Array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

View Slice Before Broadcasting:
[[1 2]
 [4 5]]

Original Array (array_a) After Broadcasting:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]

View Slice (view_b) After Broadcasting:
[[ 6  7]
 [ 9 10]]


In [ ]:
##Q.79) Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2)
##        from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
import numpy as np

# Create a NumPy array of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Print the original array and the reshaped view before modification
print("Original Array (orig_array):")
print(orig_array)
print("\nReshaped View Before Modification (reshaped_view):")
print(reshaped_view)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

# Print the original array and the reshaped view after modification
print("\nOriginal Array (orig_array) After Modification:")
print(orig_array)
print("\nReshaped View After Modification (reshaped_view):")
print(reshaped_view)

Original Array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped View Before Modification (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Original Array (orig_array) After Modification:
[[100   2   3   4]
 [  5   6   7   8]]

Reshaped View After Modification (reshaped_view):
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [ ]:
## Q. 80) Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
##         elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
import numpy as np

# Create a NumPy array of shape (3, 4) with random integers between 1 and 10
data = np.random.randint(1, 11, size=(3, 4))

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Print the original array and the copy before modification
print("Original Array (data):")
print(data)
print("\nCopy of Elements Greater Than 5 (data_copy) Before Modification:")
print(data_copy)

# Modify an element in data_copy
data_copy[0] = 100

# Print the original array and the copy after modification
print("\nOriginal Array (data) After Modification:")
print(data)
print("\nCopy of Elements Greater Than 5 (data_copy) After Modification:")
print(data_copy)

Original Array (data):
[[8 6 9 5]
 [6 9 5 3]
 [2 4 3 9]]

Copy of Elements Greater Than 5 (data_copy) Before Modification:
[8 6 9 6 9 9]

Original Array (data) After Modification:
[[8 6 9 5]
 [6 9 5 3]
 [2 4 3 9]]

Copy of Elements Greater Than 5 (data_copy) After Modification:
[100   6   9   6   9   9]


In [ ]:
##Q.81) Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
import numpy as np

# Create two matrices A and B of identical shape with integers
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition_result = A + B

# Perform element-wise subtraction
subtraction_result = A - B

# Print the original matrices and the results
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition Result (A + B):")
print(addition_result)
print("\nSubtraction Result (A - B):")
print(subtraction_result)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

Addition Result (A + B):
[[ 8 10 12]
 [14 16 18]]

Subtraction Result (A - B):
[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
## Q. 82) Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
import numpy as np

# Create matrix C (3x2)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Create matrix D (2x4)
D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

# Perform matrix multiplication
result = np.dot(C, D)

print("Matrix C:\n", C)
print("Matrix D:\n", D)
print("Result of matrix multiplication:\n", result)

Matrix C:
 [[1 2]
 [3 4]
 [5 6]]
Matrix D:
 [[ 7  8  9 10]
 [11 12 13 14]]
Result of matrix multiplication:
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [ ]:
## Q.83) Create a matrix `E` and find its transpose.
import numpy as np

# Create a matrix E with specific values
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Find the transpose of matrix E
E_transpose = E.T  # Alternatively, you can use np.transpose(E)

# Print the original matrix and its transpose
print("Matrix E:")
print(E)
print("\nTranspose of Matrix E:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
## Q.84) Generate a square matrix `F` and compute its determinant.
import numpy as np

# Generate a square matrix F (e.g., 3x3) with random integers
F = np.random.randint(1, 10, size=(3, 3))

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the matrix and its determinant
print("Matrix F:")
print(F)
print("\nDeterminant of Matrix F:")
print(determinant_F)

Matrix F:
[[7 5 3]
 [3 8 1]
 [1 5 7]]

Determinant of Matrix F:
277.99999999999994


In [ ]:
## Q. 85) Create a square matrix `G` and find its inverse.
import numpy as np

# Create a square matrix G (e.g., 3x3) with specific values
G = np.array([[4, 7, 2],
              [3, 6, 1],
              [2, 5, 3]])

# Compute the inverse of matrix G
try:
    G_inverse = np.linalg.inv(G)
    print("Matrix G:")
    print(G)
    print("\nInverse of Matrix G:")
    print(G_inverse)
except np.linalg.LinAlgError:
    print("Matrix G is singular and cannot be inverted.")

Matrix G:
[[4 7 2]
 [3 6 1]
 [2 5 3]]

Inverse of Matrix G:
[[ 1.44444444 -1.22222222 -0.55555556]
 [-0.77777778  0.88888889  0.22222222]
 [ 0.33333333 -0.66666667  0.33333333]]
